### ISSUE TITLE
What's your discord?

### ISSUE THREAD

**Issue by fionnn** [Nathaniel-428/TotalNathanielMod#10]
Hi Nathaniel,

If we are to be working together and close on this project I request your discord for better communication. I will make a group chat with myself, you, and speed so we can discuss the development and where we plan to go with this project.

Please add me on discord: fionn#0001

**Comment by fionnn** [comment]
Would like a response on this.

**Comment by Nathaniel-428** [comment]
n_a_t_h_a_n_28#5260

**Comment by fionnn** [comment]
\Added
