### ISSUE TITLE
hello son.

### ISSUE THREAD

**Issue by nathenialsdad428** [Nathaniel-428/TotalNathanielMod#11]
we need to talk. 

me and your mother have been talking and we've collectively decided to put you up for adoption, not that you'd sell its just that i've had enough of getting complaints about your rude sexual tendencies with girls. we've even had several visits from police officers complaining about a certain minecraft server and your abhorrent behaviour.

why do you suck at finding woman i dont get it. when i was a lad your age i was sleeping on a floor with hoes and gave my respects all the way. you on the otherhand harass a minecraft pig and say shit about murdering her and the man behind the slaughter. i dont get it. 

overall you dissapoint me. we're selling your computer and taking away your chinese vpns. and we're sending you to the authorities. Oh i said "adopted" nah you wouldn't find a couple that would take you especially because the fact that you're two years off from becoming a grown ass adult yet you harass other woman thats not adult. 

so me and your mom have decided to hand you over to the authorities. you're going to become a prison bitch just like you've always wanted to be. 

dont drop the soap in there will you, we wouldn't want **that** to happen would we

-- dad

**Comment by nathenialsdad428** [comment]
ps: i didn't know you were a furry, bleh

**Comment by Nathaniel-428** [comment]
Dad, you know I'm under special needs right? Which means that it's much harder for me to be put for adoption

**Comment by nathenialsdad428** [comment]
No son, im sending you to the authorities. not adoption

**Comment by Nathaniel-428** [comment]
Huh, no wonder why there are words that say BUSTED in front of my face.
