### ISSUE TITLE
Inquiry for Developer

### ISSUE THREAD

**Issue by ajaxvp** [Nathaniel-428/TotalNathanielMod#12]
Hello good sir. Today, I would like to request to become a part of this coding organization. I've seen you and your colleagues' work and I am absolutely stunned. May I please join?

**Comment by fionnn** [comment]
Object

**Comment by ghost** [comment]
he is my daddy

**Comment by Nathaniel-428** [comment]
Alright, welcome to the team

**Comment by Lyicx** [comment]
strong vouch, this man has clearly demonstrated his craft in vbs and batch

**Comment by ghost** [comment]
he is my daddy

**Comment by Nathaniel-428** [comment]
Sorry super, but you don't meet my expectations...

**Comment by fionnn** [comment]
I'm reopening this. After seeing some of your work I believe you would be an extraordinary member of development.

Vouch.

**Comment by ajaxvp** [comment]
> I'm reopening this. After seeing some of your work I believe you would be an extraordinary member of development.
> 
> Vouch.

Thank you Fionn.

**Comment by ghost** [comment]
Suckle suckle

**Comment by Nathaniel-428** [comment]
ACCEPTED

Welcome to the team!
