### ISSUE TITLE
i have decided to change my ways

### ISSUE THREAD

**Issue by Lyicx** [Nathaniel-428/TotalNathanielMod#13]
nathaniel if you let me and bowie be developer i will hand you bowie to do with as you please

**Comment by fionnn** [comment]
Object

**Comment by fionnn** [comment]
Vouchinng

**Comment by Nathaniel-428** [comment]
Was bowie even your wife?

**Comment by ghost** [comment]
Vouch, I've seen some of your work. Absolutely phenomenal and wouod love to have him on the team.

**Comment by ghost** [comment]
Would

**Comment by ajaxvp** [comment]
Vouch.

**Comment by Lyicx** [comment]
yeah fionn is my wife i told you we had hot sex last night

**Comment by Nathaniel-428** [comment]
> 
> 
> yeah fionn is my wife i told you we had hot sex last night

I know, you didn't have to tell me.

**Comment by Lyicx** [comment]
what about bowie?

**Comment by bowie7** [comment]
what about me :(

**Comment by Nathaniel-428** [comment]
Alright here you go sorry bowie
