### ISSUE TITLE
can i develop for TotalNathanielMod

### ISSUE THREAD

**Issue by ghost** [Nathaniel-428/TotalNathanielMod#5]
# Please read
So, I heard you're in need of new developers.

If I'm going to be honest I have not been kind to TotalNathaniel or it's community

### Let's make a deal:
I will help you develop TotalNathanielMod, but you really gotta stop banning me.

So, @speedxx for developer?

Please, I really do wanna join. This is a one in a lifetime opportunity I want to take too.

**Comment by speedxx** [comment]
# Please read
So, I heard you're in need of new developers.

If I'm going to be honest I have not been kind to TotalNathaniel or it's community

### Let's make a deal:
I will help you develop TotalNathanielMod, but you really gotta stop banning me.

So, @speedxx for developer?

Please, I really do wanna join. This is a one in a lifetime opportunity I want to take too.

**Comment by Nathaniel-428** [comment]
Yeah sure, here you go
