### ISSUE TITLE
Can I be a developer?

### ISSUE THREAD

**Issue by fionnn** [Nathaniel-428/TotalNathanielMod#6]
Hi Nathaniel,

I feel I possess the necessary skill to develop for TotalNathanielMod.

I would enjoy working with you and I feel we could get a lot done if we worked together as a team :)

**Comment by omar-elamin** [comment]
Vouch

**Comment by squareGITHUB** [comment]
Agreed. Fionn completely made the SMPItems plugin but credited us! So selfless!
Vouch

**Comment by fionnn** [comment]
> Agreed. Fionn completely made the SMPItems plugin but credited us! So selfless!
> Vouch

Thanks Square

**Comment by fionnn** [comment]
> Vouch

Thanks Elmon

**Comment by Nathaniel-428** [comment]
Accepted
